### ISSUE TITLE
大佬求链接

### ISSUE THREAD

**Issue by AWDSCAN** [Harmoc/CTFTools#11]
大佬，那个链接没了

**Comment by BreakALegCml** [comment]
有了嘛，没有的话我发你一下，我这边存的有一份

**Comment by BreakALegCml** [comment]
> 有了嘛，没有的话我发你一下，我这边存的有一份

有了嘛，没有的话我发你一下，我这边存的有一份

**Comment by AWDSCAN** [comment]
没

**Comment by AWDSCAN** [comment]
> > 有了嘛，没有的话我发你一下，我这边存的有一份
> 
> 有了嘛，没有的话我发你一下，我这边存的有一份

**Comment by yeshuhuai** [comment]
大佬，您还在吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月21日 10:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Harmoc/CTFTools] 大佬求链接 (Issue #11) |

有了嘛，没有的话我发你一下，我这边存的有一份

有了嘛，没有的话我发你一下，我这边存的有一份

**Comment by AWDSCAN** [comment]
> > 有了嘛，没有的话我发你一下，我这边存的有一份
> 
> 有了嘛，没有的话我发你一下，我这边存的有一份

大佬，您还在吗？

**Comment by BreakALegCml** [comment]
刚看到，不好意思，你现在找到了嘛

**Comment by AWDSCAN** [comment]
> 刚看到，不好意思，你现在找到了嘛
没有啊，大佬

**Comment by BreakALegCml** [comment]
稍等，我传到阿里云

**Comment by AWDSCAN** [comment]
> 稍等，我传到阿里云

好的，感谢大佬

**Comment by Harmoc** [comment]
已知，近期会补一下
