### ISSUE TITLE
取证大师

### ISSUE THREAD

**Issue by fralychen** [Harmoc/CTFTools#4]
提示：试用期已过，或未检测到有效U盘，程序无法运行

**Comment by Nixiabing** [comment]
同求助，不知道怎么解决。

**Comment by Harmoc** [comment]
> 提示：试用期已过，或未检测到有效U盘，程序无法运行

试一下修改本机时间

**Comment by Xunflash** [comment]
> > 提示：试用期已过，或未检测到有效U盘，程序无法运行
> 
> 试一下修改本机时间

改成什么时候呢？

**Comment by Github3362** [comment]
提示：试用期已过，或未检测到有效U盘，程序无法运行
试一下修改本机时间,可以出个教程吗
